// ─── Lexicon ────────────────────────────────────────────────────────────────
// Valence scores range from -4 (extremely negative) to +4 (extremely positive)

const LEXICON = {
  // Strongly Positive
  outstanding: 3.8,
  excellent: 3.5,
  amazing: 3.5,
  fantastic: 3.5,
  wonderful: 3.5,
  brilliant: 3.5,
  superb: 3.5,
  exceptional: 3.5,
  incredible: 3.5,
  magnificent: 3.5,
  phenomenal: 3.5,
  spectacular: 3.5,
  extraordinary: 3.5,
  splendid: 3.2,
  awesome: 3.2,
  marvelous: 3.2,
  delightful: 3.2,
  terrific: 3.0,
  perfect: 3.5,
  flawless: 3.2,
  love: 3.0,
  adore: 3.2,
  cherish: 3.0,
  passionate: 2.8,
  thrilled: 2.8,
  ecstatic: 3.5,
  elated: 3.2,
  overjoyed: 3.5,
  jubilant: 3.2,
  euphoric: 3.5,

  // Moderately Positive
  good: 1.9,
  great: 3.1,
  nice: 1.8,
  lovely: 2.5,
  happy: 2.7,
  joyful: 2.8,
  cheerful: 2.5,
  pleased: 2.0,
  satisfied: 2.0,
  glad: 2.1,
  thankful: 2.2,
  grateful: 2.4,
  hopeful: 1.9,
  optimistic: 2.2,
  confident: 1.8,
  enjoyable: 2.2,
  fun: 1.9,
  pleasant: 2.0,
  positive: 1.9,
  successful: 2.2,
  effective: 1.8,
  helpful: 1.9,
  useful: 1.7,
  valuable: 1.9,
  impressive: 2.4,
  elegant: 2.1,
  beautiful: 2.9,
  pretty: 2.0,
  charming: 2.3,
  friendly: 2.0,
  kind: 2.1,
  caring: 2.0,
  supportive: 2.0,
  reliable: 1.9,
  trustworthy: 2.1,
  honest: 1.9,
  fair: 1.6,
  better: 1.5,
  best: 3.0,
  improved: 1.6,
  progress: 1.5,
  innovative: 2.0,
  creative: 1.9,
  smart: 1.8,
  clever: 1.8,
  recommended: 1.7,
  approve: 1.5,
  endorse: 1.7,
  prefer: 1.2,
  enjoy: 2.0,
  like: 1.4,
  appreciate: 1.9,
  worthy: 1.7,
  safe: 1.5,
  secure: 1.6,
  clean: 1.4,
  clear: 1.2,
  fresh: 1.5,
  exciting: 2.3,
  enthusiastic: 2.5,
  motivated: 2.0,
  inspired: 2.2,
  productive: 1.8,
  efficient: 1.7,
  powerful: 1.8,
  robust: 1.7,
  smooth: 1.4,
  easy: 1.5,
  simple: 1.2,
  quick: 1.1,
  fast: 1.2,
  free: 1.0,
  open: 0.9,
  flexible: 1.3,
  generous: 2.0,
  brave: 2.0,
  courageous: 2.2,
  strong: 1.5,
  capable: 1.4,
  skilled: 1.7,
  compassionate: 2.3,
  loyal: 2.0,
  dedicated: 2.0,
  committed: 1.8,

  // Mildly Positive
  ok: 0.9,
  okay: 0.9,
  fine: 0.6,
  decent: 0.9,
  acceptable: 0.9,
  adequate: 0.5,
  reasonable: 0.7,
  stable: 0.8,
  steady: 0.7,
  manageable: 0.5,
  appropriate: 0.7,

  // Neutral/Objective (near-zero scores)
  new: 0.1,
  different: 0.0,
  various: 0.0,
  many: 0.0,

  // Mildly Negative
  mediocre: -1.2,
  dull: -1.0,
  boring: -1.2,
  bland: -1.0,
  weak: -1.2,
  slow: -1.1,
  outdated: -1.3,
  expensive: -1.2,
  complicated: -1.1,
  difficult: -1.0,
  confusing: -1.3,
  unclear: -1.1,
  limited: -0.9,
  lacking: -1.2,
  poor: -1.9,
  bad: -2.0,
  wrong: -1.5,
  mistake: -1.5,
  error: -1.4,
  problem: -1.3,
  issue: -1.0,
  concern: -1.0,
  trouble: -1.3,
  worry: -1.3,
  disappointing: -2.2,
  disappointed: -2.0,
  frustrating: -2.0,
  frustrated: -1.9,
  annoying: -1.8,
  annoyed: -1.6,
  upset: -1.8,
  unhappy: -2.0,
  sad: -2.1,
  unfortunate: -1.8,
  regret: -1.9,
  regrettable: -2.0,
  failure: -2.1,
  fail: -1.8,
  failed: -2.0,
  wrong: -1.5,
  broken: -1.9,
  defective: -2.0,
  flawed: -1.7,
  worse: -1.9,
  worst: -3.2,
  inferior: -2.1,
  substandard: -2.0,
  inadequate: -1.6,
  unacceptable: -2.2,
  unreliable: -1.9,
  difficult: -1.2,
  hard: -1.0,
  tough: -1.0,
  challenging: -0.8,
  complex: -0.7,
  risky: -1.5,
  dangerous: -2.2,
  harmful: -2.4,
  negative: -1.4,
  critical: -1.0,

  // Moderately Negative
  terrible: -3.0,
  horrible: -3.2,
  awful: -3.1,
  dreadful: -2.9,
  horrific: -3.2,
  atrocious: -3.5,
  appalling: -3.2,
  abysmal: -3.5,
  disgusting: -3.1,
  revolting: -3.2,
  repulsive: -3.0,
  offensive: -2.7,
  unpleasant: -2.1,
  nasty: -2.5,
  vile: -3.0,
  inferior: -2.1,
  incompetent: -2.5,
  useless: -2.5,
  worthless: -2.8,
  pointless: -2.0,
  waste: -2.2,
  spam: -1.8,
  fake: -2.0,
  dishonest: -2.5,
  corrupt: -3.0,
  manipulative: -2.8,
  deceptive: -2.7,
  unfair: -1.9,
  cruel: -3.1,
  brutal: -2.8,
  violent: -2.9,
  aggressive: -2.0,
  hostile: -2.7,
  hateful: -3.2,
  racist: -3.5,
  abusive: -3.3,
  toxic: -2.9,
  evil: -3.2,
  sinister: -2.8,
  wicked: -3.0,
  greedy: -2.4,
  selfish: -2.2,
  arrogant: -2.3,
  rude: -2.4,

  // Strongly Negative
  catastrophic: -3.5,
  devastating: -3.5,
  disastrous: -3.5,
  unbearable: -3.2,
  intolerable: -3.2,
  inexcusable: -3.3,
  outrageous: -3.0,
  despicable: -3.5,
  malicious: -3.2,
  terrifying: -3.0,
  frightening: -2.8,
  alarming: -2.5,
  shocking: -2.3,
  disgraceful: -3.0,
  shameful: -2.8,
  hate: -3.0,
  loathe: -3.2,
  despise: -3.2,
  detest: -3.0,
  abhor: -3.2,
  horrified: -3.2,
  furious: -3.0,
  enraged: -3.2,
  devastated: -3.2,
  heartbroken: -3.0,
  miserable: -3.0,
  agonizing: -3.2,

  // --- Added Extended Lexicon ---
  // Strongly Positive
  breathtaking: 3.5,
  captivating: 3.0,
  stunning: 3.2,
  dazzling: 3.2,
  fascinating: 2.8,
  radiant: 2.5,
  luminous: 2.5,
  glorious: 3.0,
  triumphant: 3.2,
  victorious: 3.0,
  thrilling: 2.9,
  exhilarating: 3.2,
  "mind-blowing": 3.5,
  "life-changing": 3.8,
  miraculous: 3.5,
  heavenly: 3.5,
  divine: 3.5,
  magical: 3.0,
  enchanting: 2.8,
  mesmerizing: 2.7,
  spellbinding: 2.8,

  // Moderately Positive
  vibrant: 2.5,
  energetic: 2.2,
  dynamic: 2.0,
  uplifting: 2.8,
  inspiring: 2.7,
  rejuvenating: 2.5,
  refreshing: 2.3,
  soothing: 2.0,
  calming: 1.8,
  peaceful: 2.0,
  tranquil: 2.2,
  serene: 2.3,
  comforting: 2.0,
  reassuring: 1.8,
  welcoming: 2.0,
  inviting: 1.9,
  appealing: 1.8,
  attractive: 2.0,
  gorgeous: 2.8,
  handsome: 2.0,
  cute: 1.8,
  sweet: 1.9,
  adorable: 2.5,
  hilarious: 3.0,
  amusing: 2.0,
  entertaining: 2.2,
  engaging: 2.0,
  compelling: 2.1,
  rewarding: 2.5,
  fulfilling: 2.7,
  satisfying: 2.3,
  gratifying: 2.5,

  // Moderately Negative
  dumb: -1.5,
  stupid: -2.0,
  idiotic: -2.5,
  foolish: -1.8,
  silly: -1.0,
  ridiculous: -1.5,
  absurd: -1.8,
  nonsensical: -1.5,
  crazy: -1.5,
  insane: -2.0,
  mad: -1.8,
  lunatic: -2.0,
  psychotic: -2.5,
  delusional: -2.0,
  paranoid: -1.5,
  neurotic: -1.2,
  anxious: -1.5,
  nervous: -1.2,
  tense: -1.0,
  stressed: -1.5,
  overwhelmed: -1.8,
  exhausted: -1.5,
  tired: -1.0,
  fatigued: -1.2,
  drained: -1.5,
  depleted: -1.5,
  weary: -1.2,
  bored: -1.0,
  apathetic: -1.2,
  indifferent: -0.5,
  uninterested: -0.8,
  unenthusiastic: -1.0,
  unmotivated: -1.2,
  lazy: -1.5,
  sluggish: -1.2,
  lethargic: -1.5,
  slothful: -1.8,
  inactive: -0.5,
  passive: -0.5,
  docile: -0.5,
  submissive: -0.8,
  weak: -1.2,
  feeble: -1.5,
  fragile: -1.0,
  vulnerable: -1.0,
  defenseless: -1.2,
  helpless: -1.5,
  powerless: -1.5,
  impotent: -1.8,
  ineffective: -1.5,
  inefficient: -1.5,
  incompetent: -2.0,
  incapable: -1.8,
  unqualified: -1.5,
  unfit: -1.5,
  unsuitable: -1.2,
  inappropriate: -1.5,
  improper: -1.2,
  incorrect: -1.2,
  inaccurate: -1.0,
  false: -1.5,
  untrue: -1.5,

  // --- Added Domain Specific Context ---
  // Tech & Software
  bug: -1.5,
  buggy: -1.8,
  glitch: -1.5,
  glitchy: -1.5,
  crash: -2.5,
  crashes: -2.5,
  lag: -1.5,
  laggy: -1.8,
  latency: -1.2,
  clunky: -1.5,
  bloated: -1.5,
  unstable: -1.8,
  deprecated: -1.0,
  seamless: 2.5,
  intuitive: 2.2,
  "user-friendly": 2.5,
  responsive: 2.0,
  optimized: 2.2,
  fast: 2.0,
  sleek: 2.1,
  snappy: 2.0,

  // E-commerce & Reviews
  scam: -3.5,
  "rip-off": -3.0,
  overpriced: -2.0,
  cheap: -1.0,
  expensive: -1.0,
  worthless: -2.8,
  useless: -2.5,
  bargain: 2.0,
  worth: 1.5,
  steal: 2.0,
  quality: 1.5,
  durable: 1.8,
  flimsy: -1.8,
  broken: -2.5,
  defective: -2.5,
  refund: -1.5,
  return: -1.0,
  warranty: 1.0,
  recommend: 2.0,
  highly_recommend: 3.0,

  // Internet Slang & Gen Z
  lit: 2.5,
  bussin: 3.0,
  fire: 2.8,
  dope: 2.5,
  goat: 3.5,
  based: 2.5,
  sigma: 2.0,
  w: 2.5,
  slays: 2.8,
  slay: 2.8,
  mid: -1.0,
  cringe: -2.0,
  cringey: -2.0,
  sus: -1.5,
  cap: -1.5,
  "no cap": 2.0,
  trash: -2.5,
  toxic: -2.8,
  salty: -1.5,
  troll: -1.8,
  l: -2.0,
  flop: -2.0,
  ratio: -1.5,
  basic: -1.0,

  // Business / Professional
  innovative: 2.2,
  synergy: 1.5,
  disruptive: 2.0,
  streamline: 1.8,
  streamlined: 1.8,
  leverage: 1.2,
  bottleneck: -1.8,
  blocker: -1.5,
  overhead: -1.0,
  synergistic: 1.5,
  agile: 1.8,
  robust: 2.0,
  scalable: 2.0,
  cumbersome: -1.5,
  tedious: -1.5,
};

// ─── Modifier Lists ──────────────────────────────────────────────────────────

/** Intensifiers — boost the magnitude of adjacent sentiment words */
const INTENSIFIERS = {
  very: 1.3,
  extremely: 1.5,
  incredibly: 1.5,
  absolutely: 1.5,
  utterly: 1.5,
  completely: 1.4,
  totally: 1.4,
  highly: 1.3,
  really: 1.2,
  super: 1.3,
  so: 1.2,
  quite: 1.1,
  particularly: 1.2,
  especially: 1.3,
  terribly: 1.3,
  awfully: 1.3,
  remarkably: 1.4,
  exceptionally: 1.4,
  extraordinarily: 1.5,
  undeniably: 1.4,
  unbelievably: 1.5,
  deeply: 1.3,
  profoundly: 1.4,
  immensely: 1.4,
  enormously: 1.4,
  vastly: 1.3,
  hugely: 1.3,
  massively: 1.3,
  overwhelming: 1.4,
  overwhelmingly: 1.5,
  significantly: 1.2,
  substantially: 1.2,
  genuinely: 1.2,
  truly: 1.3,

  // --- Added Extended Intensifiers ---
  wildly: 1.4,
  insanely: 1.5,
  hella: 1.3,
  freaking: 1.4,
  bloody: 1.3,
  damn: 1.2,
  sooo: 1.4,
  soooo: 1.5,
  mad: 1.3,
  way: 1.2,
  ridiculously: 1.4,
  outrageously: 1.4,
  phenomenally: 1.4,
  strikingly: 1.3,
  uncommonly: 1.3,
  unusually: 1.3,
  exceedingly: 1.4,
  surpassingly: 1.4,
};

/** Diminishers — reduce the magnitude of adjacent sentiment words */
const DIMINISHERS = {
  somewhat: 0.7,
  slightly: 0.6,
  "a bit": 0.6,
  "a little": 0.6,
  "kind of": 0.7,
  kinda: 0.7,
  "sort of": 0.7,
  sorta: 0.7,
  rather: 0.8,
  fairly: 0.8,
  mostly: 0.9,
  nearly: 0.9,
  almost: 0.9,
  barely: 0.5,
  hardly: 0.5,
  marginally: 0.6,
  mildly: 0.6,
  moderately: 0.7,
  relatively: 0.8,

  // --- Added Extended Diminishers ---
  faintly: 0.6,
  weakly: 0.6,
  vaguely: 0.7,
  peripherally: 0.8,
  negligibly: 0.4,
  minimally: 0.5,
  nominally: 0.6,
  superficially: 0.7,
  partially: 0.8,
  incompletely: 0.8,
  halfway: 0.8,
  tad: 0.7,
  smidge: 0.7,
  touch: 0.7,
  hair: 0.7,
  whisper: 0.6,
  trace: 0.6,
  hint: 0.6,
  shadow: 0.6,
};

/** Negation words — flip the sentiment of the next word */
const NEGATION_WORDS = new Set([
  "not",
  "no",
  "never",
  "nothing",
  "neither",
  "nor",
  "nobody",
  "nowhere",
  "none",
  "cannot",
  "can't",
  "won't",
  "wouldn't",
  "shouldn't",
  "couldn't",
  "didn't",
  "doesn't",
  "don't",
  "isn't",
  "wasn't",
  "weren't",
  "haven't",
  "hadn't",
  "hasn't",
  "mustn't",
  "needn't",
  "without",
  "lack",
  "lacking",
  "rarely",
  "seldom",
  "hardly",
  "scarcely",
  "barely",
  "fails",
  "fail",
  "failed",
  "contrary",
  "despite",
  "against",
  "refuse",
  "refused",
  "rejection",
  "reject",
  "deny",
  "denied",

  // --- Added Extended Negations ---
  "ain't",
  "noway",
  "noways",
  "nowise",
  "nowhither",
  "unlikely",
  "impossible",
  "impossibly",
  "improbable",
  "improbably",
  "doubtful",
  "doubtfully",
  "questionable",
  "questionably",
  "infrequently",
  "occasionally",
  "sporadically",
  "inconsistently",
  "unreliably",
  "unpredictably",
  "erratically",
  "randomly",
  "haphazardly",
  "arbitrarily",
  "capriciously",
  "whimsically",
  "fickle",
  "volatile",
  "unstable",
  "insecure",
  "uncertain",
  "unsure",
  "undecided",
  "unresolved",
  "unsettled",
  "stop",
  "stops",
  "stopped",
  "stopping",
  "cease",
  "ceases",
  "ceased",
  "ceasing",
  "halt",
  "halts",
  "halted",
  "halting",
  "prevent",
  "prevents",
  "prevented",
  "preventing",
  "avoid",
  "avoids",
  "avoided",
  "avoiding",
  "escape",
  "escapes",
  "escaped",
  "escaping",
  "evade",
  "evades",
  "evaded",
  "evading",
  "elude",
  "eludes",
  "eluded",
  "eluding",
  "miss",
  "misses",
  "missed",
  "missing",
  "lose",
  "loses",
  "lost",
  "losing",
]);

export { LEXICON, INTENSIFIERS, DIMINISHERS, NEGATION_WORDS };
